# Generated by Django 5.2.8 on 2026-02-05 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sneakers/')),
                ('description', models.TextField()),
                ('model_name', models.CharField(max_length=100)),
                ('colorway', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('size', models.DecimalField(decimal_places=1, max_digits=4)),
                ('size_type', models.CharField(choices=[('US', 'US'), ('UK', 'UK'), ('EU', 'EU')], default='US', max_length=2)),
                ('condition', models.CharField(choices=[('NEW', 'New/Deadstock'), ('LIKE_NEW', 'Like New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
                ('date_sold', models.DateTimeField(blank=True, null=True)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneakers', to='Soletread.brand')),
            ],
            options={
                'ordering': ['-date_listed', 'model_name'],
            },
        ),
    ]
